name: node-workflow
# Ensure the workflow runs on schedule (Sunday at 0:00) and on push to the main branch
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0'  # Runs every Sunday at 00:00 UTC

# Use a matrix strategy to use Node.js versions 16.x and 18.x
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14, 16, 18]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up a Node.js environment using the specified node version.
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # Install the dependencies.
      - name: Install Dependencies
        run: npm install

      # Run the tests.
      - name: Run Tests
        run: npm test
        continue-on-error: true

      # Run the linter.
      - name: Run Linter
        run: npm run lint

      # Send a console message at completion.
      - name: Console Message
        run: |
          echo "Hello [username of the user who initiated the run]. You pushed to [repository_name] at $(date)."
